
project_id = "ruofpmmujppmbkzwmpqd"

[functions.tutor-tryla]
verify_jwt = true

[functions.call-gemini]
enabled = true
verify_jwt = true
import_map = "./functions/call-gemini/deno.json"
entrypoint = "./functions/call-gemini/index.ts"

[functions.generate-daily-challenge]
verify_jwt = true

[functions.complete-daily-challenge]
verify_jwt = true

[functions.send-custom-notification]
verify_jwt = false
import_map = "./functions/import_map.json"